export const OPEN_NAVBAR = "OPEN_NAVBAR";
export const CLOSE_NAVBAR = "CLOSE_NAVBAR";

export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";

export const SINGLE_PRODUCT_ERROR = "SINGLE_PRODUCT_ERROR";
export const SINGLE_PRODUCT_LOADING = "SINGLE_PRODUCT_LOADING";
export const SINGLE_PRODUCT_SUCCESS = "SINGLE_PRODUCT_SUCCESS";
