export const OPEN_NAVBAR = "OPEN_NAVBAR";
export const CLOSE_NAVBAR = "CLOSE_NAVBAR";

export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";

export const SINGLE_PRODUCT_ERROR = "SINGLE_PRODUCT_ERROR";
export const SINGLE_PRODUCT_LOADING = "SINGLE_PRODUCT_LOADING";
export const SINGLE_PRODUCT_SUCCESS = "SINGLE_PRODUCT_SUCCESS";

export const PRODUCT_CARD_DESC = "PRODUCT_CARD_DESC";

export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const UPADTE_SORT = "UPADTE_SORT";
export const SORT_PRODUCTS = "SORT_PRODUCTS";
export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
